### PR TITLE
[H2Core] Cleanup MPI Linkage

### LINKED ISSUE #71: [H2Core] Logger flags require MPI linkage
The [logic for using MPI in the Logger flags](https://github.com/LLNL/DiHydrogen/blob/develop/src/utils/Logger.cpp#L15-L18) is actually incorrect. Finding the header is not sufficient as MPI linkage is not typically included "for free" with most compilers on most systems.

We can actually just tie right in to the DistConv MPI logic for now. Eventually H2 will require MPI, at least indirectly.

### PR DESCRIPTION
**Pull request by benson31**
Fixes a bug in the way MPI is detected for the H2 logger implementation.

Closes #71.

### CODE REVIEW

File: legacy/include/distconv/tensor/tensor_rocm.hpp [hunk 1]
```diff
@@ -1,213 +0,0 @@
-////////////////////////////////////////////////////////////////////////////////
```
Comment (bvanessen) [inline legacy/include/distconv/tensor/tensor_rocm.hpp:1]: Was this file supposed to be deleted?

Comment (benson31) [reply legacy/include/distconv/tensor/tensor_rocm.hpp:1]: Yes.
